//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DownloadDemon.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DOWNLOADDEMON_DIALOG        102
#define IDD_DIALOG_DOWNLOADDEMON        102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_SOCKETS_INIT_FAILED         103
#define IDS_AFXOLEINIT_FAILED           104
#define IDS_DROPTARGET_REGISTER_FAILED  105
#define IDS_MEMORY_ERROR                106
#define IDS_RUNNING_TERMINATE           107
#define IDS_BUTTON_NOTRUNNING           108
#define IDS_BUTTON_RUNNING              109
#define IDS_DEFAULT_USER                110
#define IDS_DEFAULT_PW                  111
#define IDS_NOTHING_TO_DOWNLOAD         112
#define IDS_MUST_SPECIFY_DOWNLOAD_DIR   113
#define IDS_REGISTRY_KEY                114
#define IDS_RUNNING_CANCEL              115
#define IDS_THREADS_RUNNING             116
#define IDS_COMPLETION_TIME             117
#define IDS_STOPPED                     118
#define IDS_FAILURE                     119
#define IDS_TIMEDOUT                    120
#define IDS_LOOKING                     121
#define IDS_NOTFOUND                    122
#define IDS_CONNECT                     123
#define IDS_ADD_FILE_DOWNLOAD           124
#define IDS_OK                          125
#define IDS_NOTSTARTED                  126
#define IDS_DEFAULTLOGIN                127
#define IDR_MAINFRAME                   128
#define IDS_DEFAULTPASSWORD             128
#define IDR_MENU                        129
#define IDR_MENU_APPLICATION            129
#define IDS_COL_STATUS                  129
#define IDD_DIALOG_SETTINGS             130
#define IDS_COL_LINK                    130
#define IDS_COL_LOGIN                   131
#define IDS_COL_PASSWORD                132
#define IDS_LINK_EXISTS                 133
#define IDS_COL_XFER_MODE               134
#define IDB_BITMAP_WAIT                 135
#define IDS_MODE_BINARY                 135
#define IDB_BITMAP_CONNECT              136
#define IDS_MODE_ASCII                  136
#define IDB_BITMAP_TRANSFER             137
#define IDD_DIALOG_STOPPING_NOTICE      137
#define IDS_RESETSTOPPEDFAILED          137
#define IDS_RESETSTOPPEDFAILEDSKIPPED   137
#define IDB_BITMAP_FINISHED             138
#define IDS_FILEEXTENSION               138
#define IDB_BITMAP_STOPPED              139
#define IDS_FILEDESCRIPTION             139
#define IDB_BITMAP_FAILED               140
#define IDS_ERRFILEOPEN                 140
#define IDB_BITMAP_TIMEDOUT             141
#define IDS_ERRFILEWRITE                141
#define IDB_BITMAP_LOOKINGFORFILE       142
#define IDS_INVALID_TIME_AT             142
#define IDB_BITMAP_NOTFOUND             143
#define IDS_INVALID_TIME_IN             143
#define IDR_POPUP_FILE_LIST             144
#define IDS_INVALID_PATH                144
#define IDD_LINK_PROPERTIES             145
#define IDS_AGREE_TERMS                 145
#define IDR_ACCELERATOR1                146
#define IDS_DEFAULT_DIALPARENT          146
#define IDS_DEFAULT_DIALBUTTON          147
#define IDD_DIALOG1                     148
#define IDS_DEFAULT_DIALSIBLING1        148
#define IDB_BITMAP_FILEOPENERR          149
#define IDS_DEFAULT_DIALSIBLING2        149
#define IDB_BITMAP_FILEWRITEERR         150
#define IDS_DEFAULT_DISCONNECTPARENT    150
#define IDD_WAIVER                      151
#define IDS_DEFAULT_DISCONNECTBUTTON    151
#define IDD_MODEM_ADVANCED              152
#define IDS_DEFAULT_DISCONNECTSIBLING1  152
#define IDS_DEFAULT_DISCONNECTSIBLING2  153
#define IDS_DEFAULT_DISCONNECTSIBLING3  154
#define IDB_BITMAP_SKIPPED              154
#define IDS_INTERNET_CONNECTIONS_KEY    155
#define IDD_DIALOG_REGISTER             155
#define IDS_DIRLOOKUPBROKE              156
#define IDD_DIALOG_STRIP_EXTENSION      156
#define IDS_DEFAULT_NODIALTONEPARENT    157
#define IDS_DEFAULT_NODIALTONEBUTTON    158
#define IDS_DEFAULT_NODIALTONESIBLING1  159
#define IDS_DEFAULT_NOANSWERPARENT      160
#define IDS_DEFAULT_NOANSWERBUTTON      161
#define IDS_DEFAULT_NOANSWERSIBLING1    162
#define IDS_SKIPPED                     163
#define IDS_DEFAULT_DIALSIBLING3        164
#define IDS_DEFAULT_NODIALTONESIBLING2  165
#define IDS_DEFAULT_NODIALTONESIBLING3  166
#define IDS_DEFAULT_BUSYPARENT          167
#define IDS_DEFAULT_BUSYBUTTON          168
#define IDS_DEFAULT_BUSYSIBLING1        169
#define IDS_SURE_DISCONNECT             170
#define IDS_SURE_CLEARLIST              171
#define IDS_LICENSE_PERIOD_OVER         172
#define IDS_INVALID_USERNAME_LICENSE    173
#define IDS_ALREADY_LICENSED            174
#define IDS_THANK_YOU                   175
#define IDS_FAILURE_GETWINDIR           176
#define IDS_EXPIRED_NOTICE              177
#define IDS_TRIAL_NOTICE                178
#define IDS_COL_STRIP                   179
#define IDS_YES                         180
#define IDS_NO                          181
#define IDS_NA                          182
#define IDS_ASK_REGISTER                183
#define IDS_INVALID_EXTENSION           184
#define IDS_EXTENSION_EXISTS            185
#define IDS_STRIP_DEFAULTS              186
#define IDS_COL_DESTINATION_DIR         187
#define IDS_DEFAULT_DESTDIR             188
#define IDS_DEFAULT_CANCELBUTTON        189
#define IDC_STATIC_DEFAULTLOGIN         1007
#define IDC_EDIT_DEFAULTLOGIN           1008
#define IDC_EDIT_DEFAULTPASSWORD        1009
#define IDC_STATIC_DEFAULTPASSWORD      1010
#define IDC_STATIC_SETTING_INFO         1011
#define IDC_COMBO_SIMULTANEOUS_DOWNLOADS 1012
#define IDC_CHECK_SMARTDOWNLOAD         1013
#define IDC_STATIC_DOWNLOAD_DIR         1014
#define IDC_EDIT_DOWNLOAD_DIR           1020
#define IDC_BUTTON_LOOKUP_DIR           1021
#define IDC_LIST_FTP_ITEMS              1023
#define IDC_CHECK_LOG_FILE              1026
#define IDC_CHECK_CLEAR_LOG_ON_START    1028
#define IDC_BUTTON_CLEAR_LOG_NOW        1029
#define IDC_CHECK_MULTIPLE_IDENTICAL    1030
#define IDC_EDIT_RETRY_TIME             1033
#define IDC_BUTTON_DOWNLOAD             1034
#define IDC_EDIT_CONNECTION_TIMEOUT     1035
#define IDC_STATIC_THREADS              1036
#define IDC_STATIC_TIMELEFT             1037
#define IDC_STATIC_MESSAGE              1038
#define IDC_EDIT_LINK                   1040
#define IDC_EDIT_LOGIN                  1041
#define IDC_EDIT_PASSWORD               1042
#define IDC_LINK                        1043
#define IDC_CHECK_SPECIFY_LOGIN_INFO    1044
#define IDC_EDIT_RETRY_COUNT            1045
#define IDC_CHECK_SPECIFY_DESTINATIONDIR 1045
#define IDC_COMBO_XFER_MODE             1046
#define IDC_COMBO_WHENDOWNLOAD          1047
#define IDC_CHECK_DISCONNECTDONE        1049
#define IDC_COMBO_STARTTIME             1050
#define IDC_STATIC_WAIVER               1051
#define IDC_STATIC_WAIVER2              1052
#define IDC_STATIC_WAIVER3              1053
#define IDC_STATIC_THANKYOU             1054
#define IDC_CHECK_DISABLE_LIABILITY     1056
#define IDC_BUTTON_MODEMSTRINGS         1057
#define IDC_BUTTON_DEFAULT              1061
#define IDC_EDIT_PARENT                 1062
#define IDC_EDIT_BUTTON                 1063
#define IDC_EDIT_SIBLING1               1064
#define IDC_CHECK_PARTIAL_PARENT        1065
#define IDC_CHECK_DIALMODEM             1066
#define IDC_COMBO_DIALCONNECTION        1067
#define IDC_CHECK_MINIMIZEDIALUP        1068
#define IDC_CHECK_PARTIAL_SIBLING1      1068
#define IDC_STATIC_BACKGROUND           1069
#define IDC_CHECK_PARTIAL_BUTTON        1069
#define IDC_COMBO_MODEMSCREEN           1070
#define IDC_RADIO_DUPE_OVERWRITE        1071
#define IDC_EDIT_SIBLING2               1072
#define IDC_RADIO_DUPE_SKIP             1072
#define IDC_CHECK_PARTIAL_SIBLING2      1073
#define IDC_EDIT_USERNAME               1073
#define IDC_EDIT_SIBLING3               1074
#define IDC_EDIT_LICENSE                1074
#define IDC_CHECK_PARTIAL_SIBLING3      1075
#define IDC_BUTTON_CANCEL               1075
#define IDC_STATIC_NOTICE               1076
#define IDC_COMBO_STRIP                 1077
#define IDC_BUTTON_MANAGE_STRIP_EXTENSIONS 1079
#define IDC_LIST_EXTENSIONS             1080
#define IDC_EDIT_ADD_EXTENSION          1081
#define IDC_BUTTON_ADD_EXTENSION        1082
#define IDC_BUTTON_REMOVE_EXTENSION     1083
#define IDC_EDIT_DESTINATION_DIRECTORY  1086
#define IDC_BUTTON_LOOKUP_DESTDIR       1088
#define ID_MENU_EXIT                    32772
#define ID_MENU_SETTINGS                32773
#define ID_MENU_ABOUT                   32774
#define ID_DELETE_SELECTED_FILE         32775
#define ID_PROPERTIES_SELECTED_FILE     32776
#define ID_ADD_NEW_FILE                 32777
#define ID_DELETE_COMPLETED_ITEMS       32778
#define ID_MENU_OPEN_LIST               32779
#define ID_MENU_SAVE_LIST               32780
#define ID_MENU_SAVE_LIST_AS            32781
#define ID_MENU_REGISTER                32782
#define ID_MENU_NEW_LIST                32784
#define ID_REGISTER                     32785
#define AFX_IDS_APP_REGCODE             0xE000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
